# AMREX_HOME defines the directory in which we will find all the AMReX code.
# If you set AMREX_HOME as an environment variable, this line will be ignored
AMREX_HOME ?=/Users/matt/amrex
ETI_HOME ?= ../..

DEBUG     = FALSE
USE_MPI   = TRUE
USE_OMP   = FALSE

COMP      = gnu
DIM       = 1

USE_BOLTZMANN = TRUE

include ../Make.ETI
